name: my_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  sqflite: any
  path_provider: any
  intl: ^0.17.0
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
    
   

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/licon.png"

flutter_native_splash:
  color: "#3A4664"
  image: images/spl3.png
  android_gravity: center
  android: true
  ios: true

  
  flutter_lints: ^1.0.0



flutter:

  uses-material-design: true

 
  assets:
    - images/
  